IF (@IS_EXIST_GOODS=0) /*and (@USE_DIAGN_REPORT = 0 /*or (@SERVICE=1 and @USE_DIAGN_REPORT=1)*/)*/ --если не выбраны коды АП то загружаем услуги
				BEGIN
					IF (@USE_DIAGN_REPORT=0)
						BEGIN
							insert into #SERVICES
							SELECT  
								SECTION_NUMBER = 2,  
								ORDER_BY = 7,--0,  
								ID_TABLE = 19,  
								TABLE_NAME = 'Выручка итого в т.ч.',  
								CONTRACTOR = '',  
								SECTION_NAME = 'в т.ч. услуга  итого', -- CONVERT(VARCHAR(6),CH.DATE_CHEQUE,104) + right(convert(varchar(4),datepart(yyyy,CH.DATE_CHEQUE)),2),
								DOC_NUM = CONVERT(VARCHAR(8),CH.DATE_CHEQUE,4),
								DOC_NUM_SUP='',  
								DATE_DOC = getdate(),--CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,CS.DATE_CLOSE))),104),  
						--        DATE_SHORT = '',
								PREFIX = '',
						--        PREFIX = '',
								SUM_ACC = ISNULL(SUM(CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM),0), --сумма наличных продаж  
								SUM_SUP = CONVERT(MONEY,0),  
								SVAT_SUP = CONVERT(MONEY,0),  
								SUM_ACC_0 = ISNULL(SUM(CASE WHEN CONVERT(BIGINT,TAX_RATE) = 0 THEN CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM ELSE 0 END),0),  
								SUM_ACC_10 = ISNULL(SUM(CASE WHEN CONVERT(BIGINT,TAX_RATE) = 10 THEN CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM ELSE 0 END),0),  
								SUM_ACC_18 = ISNULL(SUM(CASE WHEN CONVERT(BIGINT,TAX_RATE) = 18 THEN CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM ELSE 0 END),0),  
								SUM_SUP_0 = CONVERT(MONEY,0),  
								SUM_SUP_10 = CONVERT(MONEY,0),  
								SUM_SUP_18 = CONVERT(MONEY,0),
								CASH='',
								KIND='',
								RETURN_OR_BUY = '',
								DATE_GR = null
							FROM CASH_SESSION CS WITH(NOLOCK)  
							INNER JOIN CASH_REGISTER CR WITH(NOLOCK) ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER  
							INNER JOIN CONTRACTOR C WITH(NOLOCK) ON CR.ID_CONTRACTOR = C.ID_CONTRACTOR  
							INNER JOIN CHEQUE CH WITH(NOLOCK) ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL  
							INNER JOIN CHEQUE_ITEM CH_I WITH(NOLOCK) ON CH_I.ID_CHEQUE_GLOBAL = CH.ID_CHEQUE_GLOBAL  
							INNER JOIN SERVICE_4_SALE_ITEM S4S WITH(NOLOCK) ON S4S.ID_SERVICE_4_SALE = CH_I.ID_LOT_GLOBAL  
							inner JOIN SERVICE S WITH(NOLOCK) ON S.ID_SERVICE = S4S.ID_SERVICE  
							inner JOIN TAX_TYPE TT WITH(NOLOCK) ON TT.ID_TAX_TYPE = S.ID_TAX_TYPE  
							WHERE 
							    ch.DATE_CHEQUE BETWEEN @date_fr AND @date_to 
								AND C.ID_CONTRACTOR = @ID_AU 
								AND CH.DOCUMENT_STATE = 'PROC'  
								AND DBO.FN_CHECQUE_TYPE_PAYMENT2(CH.ID_CHEQUE_GLOBAL) IN ('TYPE1','TYPE2','TYPE3')
							GROUP BY CONVERT(VARCHAR(8),CH.DATE_CHEQUE,4)
							having   ISNULL(SUM(CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM),0)>0
						END
							ELSE
								 BEGIN
								-- IF (@SERVICE=1)
									insert into #SERVICES
									SELECT  
										SECTION_NUMBER = 2,  
										ORDER_BY = 7.5,--0,  
										ID_TABLE = 19,  
										TABLE_NAME = 'Выручка итого в т.ч.',  
										CONTRACTOR = '',  
										SECTION_NAME = '',--'в т.ч. услуга  итого',  
										DOC_NUM =CH.ID_CHEQUE,--CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,CH.DATE_CHEQUE))),104),--'№ '+SUBSTRING(AD.DOC_NUM,LEN(AD.DOC_NUM)-7,8)+' от '+ CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,DM.DATE_OP))),104),  
										DOC_NUM_SUP='',  
										DATE_DOC = null,--getdate(),--CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,CS.DATE_CLOSE))),104),  
								--        DATE_SHORT = '',
										PREFIX = '',
								--        PREFIX = '',
										SUM_ACC = ISNULL(SUM(CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM),0), --сумма наличных продаж  
										SUM_SUP = CONVERT(MONEY,0),  
										SVAT_SUP = CONVERT(MONEY,0),  
										SUM_ACC_0 = ISNULL(SUM(CASE WHEN CONVERT(BIGINT,TAX_RATE) = 0 THEN CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM ELSE 0 END),0),  
										SUM_ACC_10 = ISNULL(SUM(CASE WHEN CONVERT(BIGINT,TAX_RATE) = 10 THEN CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM ELSE 0 END),0),  
										SUM_ACC_18 = ISNULL(SUM(CASE WHEN CONVERT(BIGINT,TAX_RATE) = 18 THEN CASE WHEN CH.CHEQUE_TYPE='SALE' THEN 1 ELSE -1 END * CH_I.SUMM ELSE 0 END),0),  
										SUM_SUP_0 = CONVERT(MONEY,0),  
										SUM_SUP_10 = CONVERT(MONEY,0),  
										SUM_SUP_18 = CONVERT(MONEY,0),
										CASH = CR.NAME_CASH_REGISTER,
										KIND = '3 услуги из них',
										RETURN_OR_BUY = CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN  '2 по возврату' ELSE '1 по продаже' END,
										DATE_GR = convert(datetime,floor(CONVERT(MONEY,CH.DATE_CHEQUE)))--CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,CH.DATE_CHEQUE))),104)
										
									FROM CASH_SESSION CS WITH(NOLOCK)  
									INNER JOIN CASH_REGISTER CR WITH(NOLOCK) ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER  
									INNER JOIN CONTRACTOR C WITH(NOLOCK) ON CR.ID_CONTRACTOR = C.ID_CONTRACTOR  
									INNER JOIN CHEQUE CH WITH(NOLOCK) ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL  
									INNER JOIN CHEQUE_ITEM CH_I WITH(NOLOCK) ON CH_I.ID_CHEQUE_GLOBAL = CH.ID_CHEQUE_GLOBAL  
									INNER JOIN SERVICE_4_SALE_ITEM S4S WITH(NOLOCK) ON S4S.ID_SERVICE_4_SALE = CH_I.ID_LOT_GLOBAL  
									inner JOIN SERVICE S WITH(NOLOCK) ON S.ID_SERVICE = S4S.ID_SERVICE  
									inner JOIN TAX_TYPE TT WITH(NOLOCK) ON TT.ID_TAX_TYPE = S.ID_TAX_TYPE  
									WHERE ch.DATE_CHEQUE BETWEEN @date_fr AND @date_to   
										  AND C.ID_CONTRACTOR = @ID_AU 
										  AND CH.DOCUMENT_STATE = 'PROC' 
										  AND DBO.FN_CHECQUE_TYPE_PAYMENT2(CH.ID_CHEQUE_GLOBAL) IN ('TYPE1','TYPE2','TYPE3') 
									GROUP BY 
								          convert(datetime,floor(CONVERT(MONEY,CH.DATE_CHEQUE))),
										  CR.NAME_CASH_REGISTER,
										  CH.ID_CHEQUE,
										  CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN  '2 по возврату' ELSE '1 по продаже' END
								 END
				END
				ELSE
				BEGIN
				IF (@USE_DIAGN_REPORT=0)
				    INSERT INTO #SERVICES  
					SELECT  
						SECTION_NUMBER = 2,  
						ORDER_BY = 7,--0,  
						ID_TABLE = 19,  
						TABLE_NAME = 'Выручка итого в т.ч.',  
						CONTRACTOR = '',  
						SECTION_NAME = 'в т.ч. услуга  итого',  
						DOC_NUM ='',  
						DOC_NUM_SUP='',  
						DATE_DOC = getdate(),--CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,CS.DATE_CLOSE))),104),  
				--        DATE_SHORT = '',
						PREFIX = '',
				--        PREFIX = '',
						SUM_ACC = CONVERT(MONEY,0), --сумма наличных продаж  
						SUM_SUP = CONVERT(MONEY,0),  
						SVAT_SUP = CONVERT(MONEY,0),  
						SUM_ACC_0 = CONVERT(MONEY,0),  
						SUM_ACC_10 =  CONVERT(MONEY,0),
						SUM_ACC_18 =  CONVERT(MONEY,0),
						SUM_SUP_0 = CONVERT(MONEY,0),  
						SUM_SUP_10 = CONVERT(MONEY,0),  
						SUM_SUP_18 = CONVERT(MONEY,0),
						CASH = '',
						KIND = '',
						RETURN_OR_BUY = '',
						DATE_GR = null
					WHERE NOT EXISTS (SELECT NULL FROM #SERVICES  WITH(NOLOCK))
					
				END
				--select getdate(), CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,getdate()))),104),CONVERT(VARCHAR,getdate(),104)
				--select * from #SERVICES
				--return
